// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: proto/subscriberstats.proto

package rest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriberStatsServiceClient is the client API for SubscriberStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriberStatsServiceClient interface {
	GetSubscriberStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubscriberStats, error)
}

type subscriberStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberStatsServiceClient(cc grpc.ClientConnInterface) SubscriberStatsServiceClient {
	return &subscriberStatsServiceClient{cc}
}

func (c *subscriberStatsServiceClient) GetSubscriberStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubscriberStats, error) {
	out := new(SubscriberStats)
	err := c.cc.Invoke(ctx, "/proto.SubscriberStatsService/GetSubscriberStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriberStatsServiceServer is the server API for SubscriberStatsService service.
// All implementations must embed UnimplementedSubscriberStatsServiceServer
// for forward compatibility
type SubscriberStatsServiceServer interface {
	GetSubscriberStats(context.Context, *Empty) (*SubscriberStats, error)
	mustEmbedUnimplementedSubscriberStatsServiceServer()
}

// UnimplementedSubscriberStatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriberStatsServiceServer struct {
}

func (UnimplementedSubscriberStatsServiceServer) GetSubscriberStats(context.Context, *Empty) (*SubscriberStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriberStats not implemented")
}
func (UnimplementedSubscriberStatsServiceServer) mustEmbedUnimplementedSubscriberStatsServiceServer() {
}

// UnsafeSubscriberStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberStatsServiceServer will
// result in compilation errors.
type UnsafeSubscriberStatsServiceServer interface {
	mustEmbedUnimplementedSubscriberStatsServiceServer()
}

func RegisterSubscriberStatsServiceServer(s grpc.ServiceRegistrar, srv SubscriberStatsServiceServer) {
	s.RegisterService(&SubscriberStatsService_ServiceDesc, srv)
}

func _SubscriberStatsService_GetSubscriberStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberStatsServiceServer).GetSubscriberStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SubscriberStatsService/GetSubscriberStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberStatsServiceServer).GetSubscriberStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriberStatsService_ServiceDesc is the grpc.ServiceDesc for SubscriberStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriberStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SubscriberStatsService",
	HandlerType: (*SubscriberStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriberStats",
			Handler:    _SubscriberStatsService_GetSubscriberStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/subscriberstats.proto",
}
